export { setLogger } from './log'
export { getMetadata } from './metadata'
export { defineTemplate } from './metadata-types'
export type { LanguageInfo } from '@kitschpatrol/tokei'
export type {
	ArduinoLibraryPropertiesCategory,
	ArduinoLibraryPropertiesData,
	ArduinoLibraryPropertiesDependencyEntry,
	ArduinoLibraryPropertiesPersonEntry,
	CargoTomlAuthorEntry,
	CargoTomlData,
	CargoTomlDependencyEntry,
	CinderCinderblockData,
	CodeMetaData,
	Credentials,
	GemspecData,
	GemSpecDependency,
	FilesystemData,
	GetMetadataOptions,
	GetMetadataTemplateOptions,
	GitConfig,
	GitData,
	GitHubData,
	InfoPlistData,
	LicenseFilesData,
	LocData,
	LocTotals,
	MetadataContext,
	MetadataFileData,
	MetascopeData,
	NpmData,
	ObsidianData,
	ObsidianManifest,
	OpenFrameworksAddonConfigData,
	OpenFrameworksInstallXmlData,
	PbxprojData,
	PomXmlData,
	PomXmlDependencyEntry,
	PomXmlLicenseEntry,
	PomXmlOrganization,
	PomXmlPersonEntry,
	PackageData,
	ProcessingLibraryPropertiesAuthorEntry,
	ProcessingLibraryPropertiesCategory,
	ProcessingLibraryPropertiesData,
	PubliccodeContactEntry,
	PubliccodeContractorEntry,
	PubliccodeData,
	PubliccodeDependencyEntry,
	PubliccodeDescription,
	ReadmeData,
	PypiData,
	PyprojectData,
	SourceName,
	Template,
	TemplateData,
	UpdatesData,
	UpdatesPackage,
} from './metadata-types'
export { templates } from './templates/index'
export type { TemplateMap, TemplateName } from './templates/index'
