export { setLogger } from './log'
export { getMetadata } from './metadata'
export { defineTemplate } from './metadata-types'
export type {
	ArduinoLibraryPropertiesData,
	CargoTomlData,
	CinderCinderblockData,
	CodeMetaData,
	CodeMetaJsonData,
	Credentials,
	FilesystemData,
	GemspecData,
	GetMetadataOptions,
	GetMetadataTemplateOptions,
	GitData,
	GitHubData,
	GoModData,
	GoreleaserData,
	InfoPlistData,
	LicenseFilesData,
	LocData,
	MetadataContext,
	MetadataFileData,
	MetascopeData,
	NpmData,
	ObsidianData,
	OpenFrameworksAddonConfigData,
	OpenFrameworksInstallXmlData,
	PackageJsonData,
	PbxprojData,
	PkgInfoData,
	PomXmlData,
	ProcessingLibraryPropertiesData,
	PubliccodeData,
	PypiData,
	PyprojectData,
	PythonSetupPyData,
	ReadmeData,
	SetupCfgData,
	SourceName,
	Template,
	TemplateData,
	UpdatesData,
} from './metadata-types'
export { templates } from './templates/index'
export type { TemplateMap, TemplateName } from './templates/index'
export type { LanguageInfo } from '@kitschpatrol/tokei'
