packages:
  - '.'
  - '!test/fixtures/**'
publicHoistPattern:
  - '@kitschpatrol/repo-config'
  - '@kitschpatrol/typescript-config'
  - case-police
  - '*cspell*'
  - '*eslint*'
  - '*knip*'
  - '*mdat*'
  - '*prettier*'
  - '*remark*'
  - '*stylelint*'
allowBuilds:
  esbuild: true
  msw: true
  tree-sitter-python: true
  tree-sitter-ruby: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@kitschpatrol/*'
