onlyBuiltDependencies:
  - esbuild
  - puppeteer
  - unrs-resolver

overrides:
  '@kitschpatrol/codemeta': link:../codemeta

publicHoistPattern:
  - '@kitschpatrol/repo-config'
  - '@kitschpatrol/typescript-config'
  - case-police
  - '*cspell*'
  - '*eslint*'
  - '*knip*'
  - '*mdat*'
  - '*prettier*'
  - '*remark*'
  - '*stylelint*'
