# -*- encoding: utf-8 -*-

=begin
#Nutanix Cluster Management APIs

#Manage Hosts, Clusters and other Infrastructure.

The version of the OpenAPI document: 4.0.2

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

$:.push File.expand_path("../lib", __FILE__)
require "nutanix_clustermgmt/version"

Gem::Specification.new do |s|
  s.name        = "nutanix_clustermgmt"
  s.version     = NutanixClustermgmt::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["ManageIQ Developers"]
  s.email       = [""]
  s.homepage    = "https://openapi-generator.tech"
  s.summary     = "Nutanix VMM API"
  s.description = "Ruby gem for Nutanix Cluster Management APIs"
  s.license     = "Apache-2.0"
  s.required_ruby_version = ">= 2.7"
  s.metadata    = {}

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  # The `git ls-files -z` loads the files in the RubyGem that have been added into git.
  gemspec = File.basename(__FILE__)
  s.files = IO.popen(%w[git ls-files -z], chdir: __dir__, err: IO::NULL) do |ls|
    ls.readlines("\x0", chomp: true).reject do |f|
      (f == gemspec) ||
        f.start_with?(*%w[bin/ test/ spec/ features/ .git .github appveyor Gemfile])
    end
  end
  s.executables   = s.files.grep(%r{\Aexe/}) { |f| File.basename(f) }
  s.require_paths = ["lib"]
end
