import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { z } from 'zod'
import type { SourceRecord } from './source'
import { defineSource } from './source'

export type MetascopeInfo = {
	/** Total scan duration in milliseconds. */
	durationMs?: number
	/** Whether the scan was performed in offline mode. */
	offline?: boolean
	/** Absolute path to the scanned project directory. */
	path?: string
	/** Whether the scan recursively processed directories. */
	recursive?: boolean
	/** Whether the scan respected ignore files (e.g., .gitignore). */
	respectIgnored?: boolean
	/** ISO 8601 timestamp of when the scan was performed. */
	scannedAt?: string
	/** Data provided to or generated by templates. */
	templateData?: unknown
	/** Version of the metascope library used. */
	version?: string
	/** Workspaces detected or processed during the scan. */
	workspaces?: string[]
}

export type MetascopeData = SourceRecord<MetascopeInfo> | undefined

const packageJsonSchema = z.object({
	version: z.string().optional(),
})

function getVersion(): string | undefined {
	try {
		const packageJsonPath = resolve(fileURLToPath(import.meta.url), '../../../package.json')
		const content = readFileSync(packageJsonPath, 'utf8')
		const parsed = packageJsonSchema.parse(JSON.parse(content))
		return parsed.version
	} catch {
		return undefined
	}
}

export const metascopeSource = defineSource<'metascope'>({
	// eslint-disable-next-line ts/require-await
	async getInputs(context) {
		return [context.options.path]
	},
	key: 'metascope',
	// eslint-disable-next-line ts/require-await
	async parseInput(input, context) {
		return {
			data: {
				durationMs: 0, // Injected later!
				offline: context.options.offline,
				path: input,
				recursive: context.options.recursive,
				respectIgnored: context.options.respectIgnored,
				scannedAt: new Date().toISOString(),
				templateData: context.options.respectIgnored,
				version: getVersion(),
				workspaces: context.workspaces,
			},
			source: input,
		}
	},
	phase: 1,
})
